/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PaywallRouteImport } from './routes/paywall'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CrisisRouteImport } from './routes/crisis'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding.welcome'
import { Route as OnboardingTrackingModeRouteImport } from './routes/onboarding.tracking-mode'
import { Route as OnboardingTimingRouteImport } from './routes/onboarding.timing'
import { Route as OnboardingStoryRouteImport } from './routes/onboarding.story'
import { Route as OnboardingScienceRouteImport } from './routes/onboarding.science'
import { Route as OnboardingRevealMirrorRouteImport } from './routes/onboarding.reveal-mirror'
import { Route as OnboardingRevealHoursRouteImport } from './routes/onboarding.reveal-hours'
import { Route as OnboardingProofRouteImport } from './routes/onboarding.proof'
import { Route as OnboardingPlanRouteImport } from './routes/onboarding.plan'
import { Route as OnboardingOpenerRouteImport } from './routes/onboarding.opener'
import { Route as OnboardingLoopRouteImport } from './routes/onboarding.loop'
import { Route as OnboardingFeelingRouteImport } from './routes/onboarding.feeling'
import { Route as OnboardingDurationRouteImport } from './routes/onboarding.duration'
import { Route as OnboardingControlRouteImport } from './routes/onboarding.control'
import { Route as OnboardingCommitRouteImport } from './routes/onboarding.commit'
import { Route as OnboardingAppsRouteImport } from './routes/onboarding.apps'
import { Route as OnboardingAnalyzingRouteImport } from './routes/onboarding.analyzing'
import { Route as OnboardingAgeRouteImport } from './routes/onboarding.age'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalEulaRouteImport } from './routes/legal.eula'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AppTodayRouteImport } from './routes/app.today'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppDebriefRouteImport } from './routes/app.debrief'
import { Route as AppCheckinRouteImport } from './routes/app.checkin'
import { Route as AdminAiQualityRouteImport } from './routes/admin.ai-quality'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PaywallRoute = PaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CrisisRoute = CrisisRouteImport.update({
  id: '/crisis',
  path: '/crisis',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingTrackingModeRoute = OnboardingTrackingModeRouteImport.update({
  id: '/tracking-mode',
  path: '/tracking-mode',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingTimingRoute = OnboardingTimingRouteImport.update({
  id: '/timing',
  path: '/timing',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStoryRoute = OnboardingStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingScienceRoute = OnboardingScienceRouteImport.update({
  id: '/science',
  path: '/science',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingRevealMirrorRoute = OnboardingRevealMirrorRouteImport.update({
  id: '/reveal-mirror',
  path: '/reveal-mirror',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingRevealHoursRoute = OnboardingRevealHoursRouteImport.update({
  id: '/reveal-hours',
  path: '/reveal-hours',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingProofRoute = OnboardingProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingPlanRoute = OnboardingPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingOpenerRoute = OnboardingOpenerRouteImport.update({
  id: '/opener',
  path: '/opener',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingLoopRoute = OnboardingLoopRouteImport.update({
  id: '/loop',
  path: '/loop',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingFeelingRoute = OnboardingFeelingRouteImport.update({
  id: '/feeling',
  path: '/feeling',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingDurationRoute = OnboardingDurationRouteImport.update({
  id: '/duration',
  path: '/duration',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingControlRoute = OnboardingControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCommitRoute = OnboardingCommitRouteImport.update({
  id: '/commit',
  path: '/commit',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingAppsRoute = OnboardingAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingAnalyzingRoute = OnboardingAnalyzingRouteImport.update({
  id: '/analyzing',
  path: '/analyzing',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingAgeRoute = OnboardingAgeRouteImport.update({
  id: '/age',
  path: '/age',
  getParentRoute: () => OnboardingRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalEulaRoute = LegalEulaRouteImport.update({
  id: '/legal/eula',
  path: '/legal/eula',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppDebriefRoute = AppDebriefRouteImport.update({
  id: '/debrief',
  path: '/debrief',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinRoute = AppCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AppRoute,
} as any)
const AdminAiQualityRoute = AdminAiQualityRouteImport.update({
  id: '/admin/ai-quality',
  path: '/admin/ai-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/crisis': typeof CrisisRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/paywall': typeof PaywallRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/ai-quality': typeof AdminAiQualityRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/debrief': typeof AppDebriefRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/today': typeof AppTodayRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/legal/eula': typeof LegalEulaRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/onboarding/age': typeof OnboardingAgeRoute
  '/onboarding/analyzing': typeof OnboardingAnalyzingRoute
  '/onboarding/apps': typeof OnboardingAppsRoute
  '/onboarding/commit': typeof OnboardingCommitRoute
  '/onboarding/control': typeof OnboardingControlRoute
  '/onboarding/duration': typeof OnboardingDurationRoute
  '/onboarding/feeling': typeof OnboardingFeelingRoute
  '/onboarding/loop': typeof OnboardingLoopRoute
  '/onboarding/opener': typeof OnboardingOpenerRoute
  '/onboarding/plan': typeof OnboardingPlanRoute
  '/onboarding/proof': typeof OnboardingProofRoute
  '/onboarding/reveal-hours': typeof OnboardingRevealHoursRoute
  '/onboarding/reveal-mirror': typeof OnboardingRevealMirrorRoute
  '/onboarding/science': typeof OnboardingScienceRoute
  '/onboarding/story': typeof OnboardingStoryRoute
  '/onboarding/timing': typeof OnboardingTimingRoute
  '/onboarding/tracking-mode': typeof OnboardingTrackingModeRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/crisis': typeof CrisisRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/paywall': typeof PaywallRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/ai-quality': typeof AdminAiQualityRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/debrief': typeof AppDebriefRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/today': typeof AppTodayRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/legal/eula': typeof LegalEulaRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/onboarding/age': typeof OnboardingAgeRoute
  '/onboarding/analyzing': typeof OnboardingAnalyzingRoute
  '/onboarding/apps': typeof OnboardingAppsRoute
  '/onboarding/commit': typeof OnboardingCommitRoute
  '/onboarding/control': typeof OnboardingControlRoute
  '/onboarding/duration': typeof OnboardingDurationRoute
  '/onboarding/feeling': typeof OnboardingFeelingRoute
  '/onboarding/loop': typeof OnboardingLoopRoute
  '/onboarding/opener': typeof OnboardingOpenerRoute
  '/onboarding/plan': typeof OnboardingPlanRoute
  '/onboarding/proof': typeof OnboardingProofRoute
  '/onboarding/reveal-hours': typeof OnboardingRevealHoursRoute
  '/onboarding/reveal-mirror': typeof OnboardingRevealMirrorRoute
  '/onboarding/science': typeof OnboardingScienceRoute
  '/onboarding/story': typeof OnboardingStoryRoute
  '/onboarding/timing': typeof OnboardingTimingRoute
  '/onboarding/tracking-mode': typeof OnboardingTrackingModeRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/crisis': typeof CrisisRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/paywall': typeof PaywallRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/ai-quality': typeof AdminAiQualityRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/debrief': typeof AppDebriefRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/today': typeof AppTodayRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/legal/eula': typeof LegalEulaRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/onboarding/age': typeof OnboardingAgeRoute
  '/onboarding/analyzing': typeof OnboardingAnalyzingRoute
  '/onboarding/apps': typeof OnboardingAppsRoute
  '/onboarding/commit': typeof OnboardingCommitRoute
  '/onboarding/control': typeof OnboardingControlRoute
  '/onboarding/duration': typeof OnboardingDurationRoute
  '/onboarding/feeling': typeof OnboardingFeelingRoute
  '/onboarding/loop': typeof OnboardingLoopRoute
  '/onboarding/opener': typeof OnboardingOpenerRoute
  '/onboarding/plan': typeof OnboardingPlanRoute
  '/onboarding/proof': typeof OnboardingProofRoute
  '/onboarding/reveal-hours': typeof OnboardingRevealHoursRoute
  '/onboarding/reveal-mirror': typeof OnboardingRevealMirrorRoute
  '/onboarding/science': typeof OnboardingScienceRoute
  '/onboarding/story': typeof OnboardingStoryRoute
  '/onboarding/timing': typeof OnboardingTimingRoute
  '/onboarding/tracking-mode': typeof OnboardingTrackingModeRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/crisis'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/paywall'
    | '/reset-password'
    | '/admin/ai-quality'
    | '/app/checkin'
    | '/app/debrief'
    | '/app/insights'
    | '/app/profile'
    | '/app/today'
    | '/checkout/return'
    | '/legal/eula'
    | '/legal/privacy'
    | '/legal/terms'
    | '/onboarding/age'
    | '/onboarding/analyzing'
    | '/onboarding/apps'
    | '/onboarding/commit'
    | '/onboarding/control'
    | '/onboarding/duration'
    | '/onboarding/feeling'
    | '/onboarding/loop'
    | '/onboarding/opener'
    | '/onboarding/plan'
    | '/onboarding/proof'
    | '/onboarding/reveal-hours'
    | '/onboarding/reveal-mirror'
    | '/onboarding/science'
    | '/onboarding/story'
    | '/onboarding/timing'
    | '/onboarding/tracking-mode'
    | '/onboarding/welcome'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/crisis'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/paywall'
    | '/reset-password'
    | '/admin/ai-quality'
    | '/app/checkin'
    | '/app/debrief'
    | '/app/insights'
    | '/app/profile'
    | '/app/today'
    | '/checkout/return'
    | '/legal/eula'
    | '/legal/privacy'
    | '/legal/terms'
    | '/onboarding/age'
    | '/onboarding/analyzing'
    | '/onboarding/apps'
    | '/onboarding/commit'
    | '/onboarding/control'
    | '/onboarding/duration'
    | '/onboarding/feeling'
    | '/onboarding/loop'
    | '/onboarding/opener'
    | '/onboarding/plan'
    | '/onboarding/proof'
    | '/onboarding/reveal-hours'
    | '/onboarding/reveal-mirror'
    | '/onboarding/science'
    | '/onboarding/story'
    | '/onboarding/timing'
    | '/onboarding/tracking-mode'
    | '/onboarding/welcome'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/crisis'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/paywall'
    | '/reset-password'
    | '/admin/ai-quality'
    | '/app/checkin'
    | '/app/debrief'
    | '/app/insights'
    | '/app/profile'
    | '/app/today'
    | '/checkout/return'
    | '/legal/eula'
    | '/legal/privacy'
    | '/legal/terms'
    | '/onboarding/age'
    | '/onboarding/analyzing'
    | '/onboarding/apps'
    | '/onboarding/commit'
    | '/onboarding/control'
    | '/onboarding/duration'
    | '/onboarding/feeling'
    | '/onboarding/loop'
    | '/onboarding/opener'
    | '/onboarding/plan'
    | '/onboarding/proof'
    | '/onboarding/reveal-hours'
    | '/onboarding/reveal-mirror'
    | '/onboarding/science'
    | '/onboarding/story'
    | '/onboarding/timing'
    | '/onboarding/tracking-mode'
    | '/onboarding/welcome'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CrisisRoute: typeof CrisisRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PaywallRoute: typeof PaywallRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminAiQualityRoute: typeof AdminAiQualityRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  LegalEulaRoute: typeof LegalEulaRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paywall': {
      id: '/paywall'
      path: '/paywall'
      fullPath: '/paywall'
      preLoaderRoute: typeof PaywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crisis': {
      id: '/crisis'
      path: '/crisis'
      fullPath: '/crisis'
      preLoaderRoute: typeof CrisisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/tracking-mode': {
      id: '/onboarding/tracking-mode'
      path: '/tracking-mode'
      fullPath: '/onboarding/tracking-mode'
      preLoaderRoute: typeof OnboardingTrackingModeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/timing': {
      id: '/onboarding/timing'
      path: '/timing'
      fullPath: '/onboarding/timing'
      preLoaderRoute: typeof OnboardingTimingRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/story': {
      id: '/onboarding/story'
      path: '/story'
      fullPath: '/onboarding/story'
      preLoaderRoute: typeof OnboardingStoryRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/science': {
      id: '/onboarding/science'
      path: '/science'
      fullPath: '/onboarding/science'
      preLoaderRoute: typeof OnboardingScienceRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/reveal-mirror': {
      id: '/onboarding/reveal-mirror'
      path: '/reveal-mirror'
      fullPath: '/onboarding/reveal-mirror'
      preLoaderRoute: typeof OnboardingRevealMirrorRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/reveal-hours': {
      id: '/onboarding/reveal-hours'
      path: '/reveal-hours'
      fullPath: '/onboarding/reveal-hours'
      preLoaderRoute: typeof OnboardingRevealHoursRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/proof': {
      id: '/onboarding/proof'
      path: '/proof'
      fullPath: '/onboarding/proof'
      preLoaderRoute: typeof OnboardingProofRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/plan': {
      id: '/onboarding/plan'
      path: '/plan'
      fullPath: '/onboarding/plan'
      preLoaderRoute: typeof OnboardingPlanRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/opener': {
      id: '/onboarding/opener'
      path: '/opener'
      fullPath: '/onboarding/opener'
      preLoaderRoute: typeof OnboardingOpenerRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/loop': {
      id: '/onboarding/loop'
      path: '/loop'
      fullPath: '/onboarding/loop'
      preLoaderRoute: typeof OnboardingLoopRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/feeling': {
      id: '/onboarding/feeling'
      path: '/feeling'
      fullPath: '/onboarding/feeling'
      preLoaderRoute: typeof OnboardingFeelingRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/duration': {
      id: '/onboarding/duration'
      path: '/duration'
      fullPath: '/onboarding/duration'
      preLoaderRoute: typeof OnboardingDurationRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/control': {
      id: '/onboarding/control'
      path: '/control'
      fullPath: '/onboarding/control'
      preLoaderRoute: typeof OnboardingControlRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/commit': {
      id: '/onboarding/commit'
      path: '/commit'
      fullPath: '/onboarding/commit'
      preLoaderRoute: typeof OnboardingCommitRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/apps': {
      id: '/onboarding/apps'
      path: '/apps'
      fullPath: '/onboarding/apps'
      preLoaderRoute: typeof OnboardingAppsRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/analyzing': {
      id: '/onboarding/analyzing'
      path: '/analyzing'
      fullPath: '/onboarding/analyzing'
      preLoaderRoute: typeof OnboardingAnalyzingRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/age': {
      id: '/onboarding/age'
      path: '/age'
      fullPath: '/onboarding/age'
      preLoaderRoute: typeof OnboardingAgeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/eula': {
      id: '/legal/eula'
      path: '/legal/eula'
      fullPath: '/legal/eula'
      preLoaderRoute: typeof LegalEulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/today': {
      id: '/app/today'
      path: '/today'
      fullPath: '/app/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/debrief': {
      id: '/app/debrief'
      path: '/debrief'
      fullPath: '/app/debrief'
      preLoaderRoute: typeof AppDebriefRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkin': {
      id: '/app/checkin'
      path: '/checkin'
      fullPath: '/app/checkin'
      preLoaderRoute: typeof AppCheckinRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/ai-quality': {
      id: '/admin/ai-quality'
      path: '/admin/ai-quality'
      fullPath: '/admin/ai-quality'
      preLoaderRoute: typeof AdminAiQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCheckinRoute: typeof AppCheckinRoute
  AppDebriefRoute: typeof AppDebriefRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTodayRoute: typeof AppTodayRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCheckinRoute: AppCheckinRoute,
  AppDebriefRoute: AppDebriefRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppProfileRoute: AppProfileRoute,
  AppTodayRoute: AppTodayRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OnboardingRouteChildren {
  OnboardingAgeRoute: typeof OnboardingAgeRoute
  OnboardingAnalyzingRoute: typeof OnboardingAnalyzingRoute
  OnboardingAppsRoute: typeof OnboardingAppsRoute
  OnboardingCommitRoute: typeof OnboardingCommitRoute
  OnboardingControlRoute: typeof OnboardingControlRoute
  OnboardingDurationRoute: typeof OnboardingDurationRoute
  OnboardingFeelingRoute: typeof OnboardingFeelingRoute
  OnboardingLoopRoute: typeof OnboardingLoopRoute
  OnboardingOpenerRoute: typeof OnboardingOpenerRoute
  OnboardingPlanRoute: typeof OnboardingPlanRoute
  OnboardingProofRoute: typeof OnboardingProofRoute
  OnboardingRevealHoursRoute: typeof OnboardingRevealHoursRoute
  OnboardingRevealMirrorRoute: typeof OnboardingRevealMirrorRoute
  OnboardingScienceRoute: typeof OnboardingScienceRoute
  OnboardingStoryRoute: typeof OnboardingStoryRoute
  OnboardingTimingRoute: typeof OnboardingTimingRoute
  OnboardingTrackingModeRoute: typeof OnboardingTrackingModeRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingAgeRoute: OnboardingAgeRoute,
  OnboardingAnalyzingRoute: OnboardingAnalyzingRoute,
  OnboardingAppsRoute: OnboardingAppsRoute,
  OnboardingCommitRoute: OnboardingCommitRoute,
  OnboardingControlRoute: OnboardingControlRoute,
  OnboardingDurationRoute: OnboardingDurationRoute,
  OnboardingFeelingRoute: OnboardingFeelingRoute,
  OnboardingLoopRoute: OnboardingLoopRoute,
  OnboardingOpenerRoute: OnboardingOpenerRoute,
  OnboardingPlanRoute: OnboardingPlanRoute,
  OnboardingProofRoute: OnboardingProofRoute,
  OnboardingRevealHoursRoute: OnboardingRevealHoursRoute,
  OnboardingRevealMirrorRoute: OnboardingRevealMirrorRoute,
  OnboardingScienceRoute: OnboardingScienceRoute,
  OnboardingStoryRoute: OnboardingStoryRoute,
  OnboardingTimingRoute: OnboardingTimingRoute,
  OnboardingTrackingModeRoute: OnboardingTrackingModeRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CrisisRoute: CrisisRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PaywallRoute: PaywallRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminAiQualityRoute: AdminAiQualityRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  LegalEulaRoute: LegalEulaRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
